<?php

namespace App\Models;

use Illuminate\Support\Facades\File;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LinkMenu extends Model
{
  use HasFactory;

  /**
   * Поля для работы с таблицей
   *
   * @var string[]
   */
  protected $fillable = [
    'name',
    'link',
    'image'
  ];

  /**
   * @return string
   */
  public function getPhoto(): string
  {
    return asset('storage/link-menu/' . $this->image);
  }
//  protected static function boot()
//  {
//    parent::boot();
//
//    LinkMenu::deleting(function (LinkMenu  $linkMenu) {
//      File::delete(public_path('storage/link-menu/' . $linkMenu->image));
//    });
//  }

  public function category ()
  {
    return $this->belongsTo(Category::class);
  }

  public function delete()
  {
    File::delete(public_path('storage/link-menu/' . $this->image));
    return parent::delete(); // TODO: Change the autogenerated stub
  }
}
