<?php
/*
 * Copyright (c) 2020.
 * The written code is completely free, full copying and modifications for improvement are allowed.
 * I am Fulliton https://github.com/ArtyshkoAndrey giving the right to everyone, without exception, to use this code.
 * Stable and optimized code =)
 */

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\File;

/**
 * App\Models\News
 *
 * @property int $id
 * @property string $image
 * @property string $content
 * @property string $description
 * @property string $title
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|News newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|News newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|News query()
 * @method static \Illuminate\Database\Eloquent\Builder|News whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|News whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|News whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|News whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|News whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|News whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|News whereUpdatedAt($value)
 * @mixin Eloquent
 */
class News extends Model
{
  use HasFactory;

  /**
   * Поля доступные для работы в таблице
   *
   * @var string[]
   */
  protected $fillable = [
    'image',
    'title',
    'content',
    'description'
  ];

  public function delete()
  {
    File::delete(public_path('storage/news/' . $this->image));
    return parent::delete(); // TODO: Change the autogenerated stub
  }
}
